/**
 * `planJourneys` — the router's public entry point, implementing the frozen
 * `PlanJourneysFn`.
 *
 * Ranking is reliability-first, duration-second (product thesis). A single CSA
 * run only ever returns one path, so candidates are generated by re-running CSA
 * with different segment bans — the standard way to get diverse paths out of a
 * connection scan:
 *
 *   1. fastest scheduled path            (applyRisk = false)
 *   2. risk-adjusted path                (applyRisk = true)
 *   3. one run per segment of (1) and (2) — forces the second-best route
 *   4. safe mode: ban every materially risky segment of a seed path
 *
 * Every candidate is then scored, de-duplicated by ride-leg signature, sorted
 * by reliability and sliced to `query.maxItineraries`.
 */

import type {
  Itinerary,
  LineId,
  PlanJourneysFn,
  PlanJourneysOptions,
  RouteQuery,
  SegmentId,
} from "@/lib/contracts";
import { MATERIAL_RISK_CONFIDENCE_THRESHOLD } from "@/lib/contracts";
import type { CompactTransitGraph } from "@/lib/gtfs/compact";
import { materializeTransitGraph } from "@/lib/gtfs/compact";
import { buildRoutingContext } from "./context";
import { emptyBanSet, runCsa, type CsaResult } from "./csa";
import { createRiskPricing } from "./risk-pricing";
import {
  buildItineraryDraft,
  buildSameStationItinerary,
  type ItineraryDraft,
} from "./itinerary";
import { explainRank } from "./reliability";

/**
 * Upper bound on how far past the requested departure time connections are
 * materialised. The longest end-to-end run in this feed is ~1h40m; 6 hours is
 * far beyond any real journey and keeps the per-query working set ~5x smaller
 * than the whole weekday graph.
 */
export const MAX_PLANNING_HORIZON_SECONDS = 6 * 3600;

const MAX_DIVERSITY_BANS_PER_SEED = 6;
const MAX_SECOND_ROUND_SEEDS = 3;
const MAX_SECOND_ROUND_BANS_PER_SEED = 4;
const MAX_PREFIX_UNION_CANDIDATES = 4;
const MAX_CANDIDATE_RUNS = 40;
const MAX_TRANSFERS_CAP = 8;

function uniqueSegmentsOf(result: CsaResult): SegmentId[] {
  const seen = new Set<SegmentId>();
  const out: SegmentId[] = [];
  for (const hop of result.hops) {
    if (hop.kind !== "CONNECTION") continue;
    const segmentId = hop.connection.segmentId;
    if (seen.has(segmentId)) continue;
    seen.add(segmentId);
    out.push(segmentId);
  }
  return out;
}

function uniqueLinesOf(result: CsaResult): LineId[] {
  const seen = new Set<LineId>();
  const out: LineId[] = [];
  for (const hop of result.hops) {
    if (hop.kind !== "CONNECTION") continue;
    const lineId = hop.connection.lineId;
    if (seen.has(lineId)) continue;
    seen.add(lineId);
    out.push(lineId);
  }
  return out;
}

function compareDrafts(a: ItineraryDraft, b: ItineraryDraft): number {
  const byReliability = b.itinerary.reliabilityScore - a.itinerary.reliabilityScore;
  if (Math.abs(byReliability) > 1e-9) return byReliability;
  const byDuration = a.itinerary.totalDurationSeconds - b.itinerary.totalDurationSeconds;
  if (byDuration !== 0) return byDuration;
  const byTransfers = a.itinerary.transferCount - b.itinerary.transferCount;
  if (byTransfers !== 0) return byTransfers;
  return a.itinerary.id.localeCompare(b.itinerary.id);
}

function finalize(draft: ItineraryDraft, rank: number, all: ItineraryDraft[]): Itinerary {
  const top = all[0].itinerary;
  const whyThisRank = explainRank({
    rank,
    total: all.length,
    reliabilityScore: draft.itinerary.reliabilityScore,
    badge: draft.itinerary.reliabilityBadge,
    p90Seconds: draft.itinerary.arrival.p90Seconds,
    totalDurationSeconds: draft.itinerary.totalDurationSeconds,
    transferCount: draft.itinerary.transferCount,
    lineLabels: draft.lineLabels,
    riskySegmentCount: draft.riskySegmentIds.length,
    maxDegradationProbability: draft.itinerary.maxDegradationProbability,
    expectedDelaySeconds: draft.itinerary.expectedDelaySeconds,
    topPickDurationSeconds: top.totalDurationSeconds,
    topPickReliabilityScore: top.reliabilityScore,
  });
  return { ...draft.itinerary, rank, whyThisRank };
}

export const planJourneys: PlanJourneysFn = (options) => {
  const { graph, query } = options;
  const pricing = createRiskPricing(options.riskLookup, options.riskPenalty);

  const originExists = graph.stations.some((s) => s.id === query.originStationId);
  const destinationExists = graph.stations.some((s) => s.id === query.destinationStationId);
  if (!originExists || !destinationExists) return [];

  if (query.originStationId === query.destinationStationId) {
    return [buildSameStationItinerary(query.originStationId, query.departAfterSeconds)];
  }

  const maxTransfers = Math.max(0, Math.min(MAX_TRANSFERS_CAP, Math.floor(query.maxTransfers)));
  // `maxItineraries` is an upper bound in the frozen contract, so 0 legitimately
  // means "return nothing" rather than "return your favourite".
  const maxItineraries = Math.max(0, Math.floor(query.maxItineraries));
  if (maxItineraries === 0) return [];

  const context = buildRoutingContext(graph, query.serviceWeekday, {
    minDepartureSeconds: query.departAfterSeconds,
    maxDepartureSeconds:
      query.departAfterSeconds + Math.max(0, query.maxInitialWaitSeconds) + MAX_PLANNING_HORIZON_SECONDS,
  });

  const originIndex = context.stationIndex.get(query.originStationId);
  const destinationIndex = context.stationIndex.get(query.destinationStationId);
  if (originIndex === undefined || destinationIndex === undefined) return [];

  const drafts = new Map<string, ItineraryDraft>();
  const seenSignatures = new Set<string>();
  let runsUsed = 0;

  const attempt = (banned: ReadonlySet<SegmentId>, applyRisk: boolean): CsaResult | null => {
    if (runsUsed >= MAX_CANDIDATE_RUNS) return null;
    runsUsed += 1;
    const result = runCsa({
      context,
      originIndex,
      destinationIndex,
      departAfterSeconds: query.departAfterSeconds,
      maxInitialWaitSeconds: query.maxInitialWaitSeconds,
      maxTransfers,
      bannedSegments: banned,
      applyRisk,
      pricing,
    });
    if (!result) return null;
    const draft = buildItineraryDraft({
      result,
      context,
      query,
      pricing,
      riskLookup: options.riskLookup,
    });
    if (!seenSignatures.has(draft.signature)) {
      seenSignatures.add(draft.signature);
      drafts.set(draft.signature, draft);
    }
    return result;
  };

  const fastest = attempt(emptyBanSet(), false);
  const riskAdjusted = attempt(emptyBanSet(), true);

  const seeds: CsaResult[] = [];
  const seedKeys = new Set<string>();
  for (const candidate of [fastest, riskAdjusted]) {
    if (!candidate) continue;
    const key = uniqueSegmentsOf(candidate).join("|");
    if (seedKeys.has(key)) continue;
    seedKeys.add(key);
    seeds.push(candidate);
  }

  const isMaterialRisk = (segmentId: SegmentId): boolean => {
    const risk = options.riskLookup ? options.riskLookup(segmentId) : undefined;
    return Boolean(risk && risk.degradationProbability >= MATERIAL_RISK_CONFIDENCE_THRESHOLD);
  };

  const banPlans: Array<ReadonlySet<SegmentId>> = [];
  const seenBanPlans = new Set<string>();
  const addBanPlan = (segmentIds: SegmentId[]): void => {
    if (segmentIds.length === 0) return;
    const key = [...segmentIds].sort().join("|");
    if (seenBanPlans.has(key)) return;
    seenBanPlans.add(key);
    banPlans.push(new Set(segmentIds));
  };

  const segmentsByLine = context.graph.segments.reduce<Map<LineId, SegmentId[]>>((acc, segment) => {
    const list = acc.get(segment.lineId);
    if (list) list.push(segment.id);
    else acc.set(segment.lineId, [segment.id]);
    return acc;
  }, new Map());

  for (const seed of seeds) {
    const segmentIds = uniqueSegmentsOf(seed);
    for (const segmentId of segmentIds.slice(0, MAX_DIVERSITY_BANS_PER_SEED)) {
      addBanPlan([segmentId]);
    }
    // Banning a whole line forces a genuinely different line combination, which
    // is what surfaces a route the per-segment bans cannot reach. It returns no
    // path when the line is unavoidable, and that is handled as a null result.
    for (const lineId of uniqueLinesOf(seed)) {
      addBanPlan(segmentsByLine.get(lineId) ?? []);
    }
    addBanPlan(segmentIds.filter(isMaterialRisk));
  }

  let nextBanPlan = 0;
  const drainBanPlans = (): void => {
    while (nextBanPlan < banPlans.length && runsUsed < MAX_CANDIDATE_RUNS) {
      const banPlan = banPlans[nextBanPlan];
      nextBanPlan += 1;
      attempt(banPlan, true);
    }
  };

  drainBanPlans();

  // Second diversity round: the first round's alternatives are themselves seeds.
  // Without this, a route that only appears after banning *two* of the fastest
  // route's lines (e.g. PYL + KGL + MR around a disrupted KJ) is never reached.
  const discovered = [...drafts.values()].sort(compareDrafts).slice(0, MAX_SECOND_ROUND_SEEDS);
  for (const draft of discovered) {
    for (const segmentId of draft.segmentIds.slice(0, MAX_SECOND_ROUND_BANS_PER_SEED)) {
      addBanPlan([segmentId]);
    }
  }
  drainBanPlans();

  // Third round: ban the UNION of the lines used by the best k alternatives.
  // Single-line bans cannot escape a two-line corridor (the fastest two routes
  // here both use KJ), and banning every line leaves no path at all; the prefix
  // union is the smallest ban that forces a wholly different line combination.
  const prefixRanked = [...drafts.values()].sort(compareDrafts).slice(0, MAX_PREFIX_UNION_CANDIDATES);
  const unionLines: LineId[] = [];
  for (const draft of prefixRanked) {
    for (const lineId of draft.lineIds) {
      if (!unionLines.includes(lineId)) unionLines.push(lineId);
    }
    const unionSegments = unionLines.flatMap((lineId) => segmentsByLine.get(lineId) ?? []);
    // Never ban every line in the network — that can only ever return null.
    if (unionLines.length < context.graph.lines.length) addBanPlan(unionSegments);
  }
  drainBanPlans();

  const candidates = [...drafts.values()];
  if (candidates.length === 0) return [];

  candidates.sort(compareDrafts);
  const limited = candidates.slice(0, maxItineraries);
  return limited.map((draft, index) => finalize(draft, index + 1, limited));
};

/** Re-exported so integration code can build a query without importing contracts twice. */
export type { RouteQuery };

/**
 * Convenience entry point for the offline client: expand only the window the
 * query needs from the compact cached artifact, then plan against it.
 *
 * Equivalent to
 *   planJourneys({ ...options, graph: materializeTransitGraph(compact, window) })
 * with the window derived from the query, so the phone never holds all ~163k
 * connections in memory.
 */
export function planJourneysFromCompact(
  compact: CompactTransitGraph,
  options: Omit<PlanJourneysOptions, "graph">,
): Itinerary[] {
  const { query } = options;
  const graph = materializeTransitGraph(compact, {
    weekday: query.serviceWeekday,
    fromSeconds: query.departAfterSeconds,
    toSeconds:
      query.departAfterSeconds +
      Math.max(0, query.maxInitialWaitSeconds) +
      MAX_PLANNING_HORIZON_SECONDS,
  });
  return planJourneys({ ...options, graph });
}
